// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJ2UY_LLv2_zVEjfQz27oFVG95ZtXkhg',
    appId: '1:326610926685:web:736dc08c54b11c6e3361b4',
    messagingSenderId: '326610926685',
    projectId: 'educationapp-842af',
    authDomain: 'educationapp-842af.firebaseapp.com',
    storageBucket: 'educationapp-842af.appspot.com',
    measurementId: 'G-DMX6S4TRQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqs1QpN1KyaZ5CZEeAQl1H2zbWoDMNWc',
    appId: '1:326610926685:android:0774a11e93e2f8293361b4',
    messagingSenderId: '326610926685',
    projectId: 'educationapp-842af',
    storageBucket: 'educationapp-842af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOAGXM_v5HbF2j9WuvM-0zDH40EzEuVgk',
    appId: '1:326610926685:ios:6309bf58d8df7e873361b4',
    messagingSenderId: '326610926685',
    projectId: 'educationapp-842af',
    storageBucket: 'educationapp-842af.appspot.com',
    iosBundleId: 'com.example.eLearing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOAGXM_v5HbF2j9WuvM-0zDH40EzEuVgk',
    appId: '1:326610926685:ios:6309bf58d8df7e873361b4',
    messagingSenderId: '326610926685',
    projectId: 'educationapp-842af',
    storageBucket: 'educationapp-842af.appspot.com',
    iosBundleId: 'com.example.eLearing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJ2UY_LLv2_zVEjfQz27oFVG95ZtXkhg',
    appId: '1:326610926685:web:080924fba9928ec73361b4',
    messagingSenderId: '326610926685',
    projectId: 'educationapp-842af',
    authDomain: 'educationapp-842af.firebaseapp.com',
    storageBucket: 'educationapp-842af.appspot.com',
    measurementId: 'G-SGECBFTFYK',
  );
}
